# Generated by Django 3.0.5 on 2020-04-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stayhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='募集タイトル')),
                ('content', models.TextField(default='なし', verbose_name='募集内容')),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='リンク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('conditions', models.IntegerField(choices=[(1, '募集中'), (2, '募集終了')], default=1, verbose_name='状態')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='募集画像')),
                ('started_at', models.TimeField(verbose_name='開始時間')),
                ('stopped_at', models.TimeField(verbose_name='終了時間')),
                ('target_day', models.DateField(verbose_name='対象日')),
                ('member_number', models.IntegerField(default=1, verbose_name='予定人数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stayhome.User')),
                ('hash_tags', models.ManyToManyField(blank=True, to='stayhome.HashTags')),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
